### ISSUE TITLE
ROS1 tools for solve tf_static issue and cmd_vel pub frequency

### ISSUE THREAD

**Issue by jginesclavero** [MROS-RobMoSys-ITP/Pilot-URJC#10]
Hi Team!

I don't know which is the best structure to upload the two created tools necessary to the correct working of the navigation2 through the ros1bridge. 

Must we create a new "Ros1Tools" repo? What do you think?

Best

**Comment by fmrico** [comment]
Let's open a repo in IntelligentRobotics organization, called Navigation2-Tiago-Support, or something like that. It is a contribution to Tiago users, and it's beyond the scope of MROS.

**Comment by jginesclavero** [comment]
Ok! I have created the repo [nav2-TIAGo-support](https://github.com/IntelligentRoboticsLabs/nav2-TIAGo-support). Closed!
