### ISSUE TITLE
stderr: bica_behavior_tree 

### ISSUE THREAD

**Issue by chcorbato** [MROS-RobMoSys-ITP/Pilot-URJC#22]
Errors compiling with current `behavior_trees` of `bica_behavior_tree`.
Avoided using [`BICA deb023b7ffa5080c962e77a56d16157d6ed901d3`](https://github.com/IntelligentRoboticsLabs/BICA/tree/deb023b7ffa5080c962e77a56d16157d6ed901d3)
```
In file included from /home/chcorbato/mros_itp_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/tree_node.h:20:0,
                 from /home/chcorbato/mros_itp_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/control_node.h:18,
                 from /home/chcorbato/mros_itp_ws/src/BICA/bica_behavior_tree/plugins/control/activation_sequence.cpp:19:
/home/chcorbato/mros_itp_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/exceptions.h: In constructor ‘BT::BehaviorTreeException::BehaviorTreeException(std::string_view)’:
/home/chcorbato/mros_itp_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/exceptions.h:27:75: error: ‘using string_view = class std::basic_string_view<char> {aka class std::basic_string_view<char>}’ has no member named ‘to_string’
     BehaviorTreeException(nonstd::string_view message):  message_(message.to_string())
...
```

**Comment by fmrico** [comment]
This is related to the C++ version. I don't remember very well, but I think I wrote an issue in behavior tree about this... I have to check it.

**Comment by marioney** [comment]
> Avoided using [`BICA deb023b7ffa5080c962e77a56d16157d6ed901d3`](https://github.com/IntelligentRoboticsLabs/BICA/tree/deb023b7ffa5080c962e77a56d16157d6ed901d3)

I tried with both the [behavior_trees]( https://github.com/IntelligentRoboticsLabs/BICA/tree/behavior_trees) branch and that one, but I'm still getting compile errors.

**Comment by marioney** [comment]
UPDATE:  with the changes mentioned in #20 and the [behavior_trees]( https://github.com/IntelligentRoboticsLabs/BICA/tree/behavior_trees) branch, I can compile everything but the  `bica_examples` which I just ignored.

**Comment by chcorbato** [comment]
> UPDATE: with the changes mentioned in #20 and the [behavior_trees](https://github.com/IntelligentRoboticsLabs/BICA/tree/behavior_trees) branch, I can compile everything but the `bica_examples` which I just ignored.

@marioney can you gather the instructions so that we can easily replicate that?
Is it a matter of updating `dependencies.repos` and the readme?
