### ISSUE TITLE
Fix Instructions for Launching in simulated turtlebot3 not working

### ISSUE THREAD

**Issue by marioney** [MROS-RobMoSys-ITP/Pilot-URJC#25]
The [instructions for running the pilot on a simulated tb3](https://github.com/MROS-RobMoSys-ITP/Pilot-URJC#launching-in-simulated-turtlebot3) are not correct.

I'm not sure if it's only because the `autostart` and `remapping` arguments are missing on the first command, because even if I run

```
ros2 launch nav2_bringup nav2_tb3_system_modes_sim_launch.py autostart:=True remappings:=True map:=[PATH TO]/map.yaml
```

I don't get a full `tf` tree or a map on `rviz` and moreover, I'm also getting the error described in #24.

For now, I'm launching the `tb3 world` separately and I'm using a copy of the [nav2_turtlebot2_launch](https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/blob/master/pilot_urjc_bringup/launch/turtlebot2_sim/nav2_turtlebot2_launch.py) for the tb3

**Comment by marioney** [comment]
The instructions on how to build and launch the pilot on a simulated tb have been updated on https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/commit/cfa69cfd658387a93ad4da2a74d57ba118e1d484

I've tested it and runs OK including changes on the system_modes

The instructions are now pointing to the[ mario-tests](https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/tree/mario-tests) branch.

@chcorbato can you test them, if they are OK we can change them to point to master and do a PR.

**Comment by chcorbato** [comment]
I think there is a typo in the new instruction to build `navigation2`, since they are the same than for the `ros2_nav_dependencies`:
 https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/blob/cfa69cfd658387a93ad4da2a74d57ba118e1d484/README.md#L51-L52

**Comment by chcorbato** [comment]
@marioney your new version of the instructions, what `ros2_eloquent` installation do they assume, binary packages or from sources? DO you need first to source your `ros2_eloquent` installation?

**Comment by fmrico** [comment]
@chcorbato I suppose that in simulation, we can use standard eloquent binary installation.

You need to compile ROS2 from sources when you are using our ROS1 <-> ROS2 bridges, when using Tiago.

**Comment by chcorbato** [comment]
> @chcorbato I suppose that in simulation, we can use standard eloquent binary installation.
> You need to compile ROS2 from sources when you are using our ROS1 <-> ROS2 bridges, when using Tiago.

Thanks @fmrico 

I have a binary installation now, but I get this error 
```
~/ros2_nav_dependencies_ws$   rosdep install -y -r -q --from-paths src --ignore-src --rosdistro eloquent
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
behaviortree_cpp_v3: Cannot locate rosdep definition for [roslib]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
```
any ideas are welcome

**Comment by fmrico** [comment]
Yes!! I am fixing that now. The idea is using the official behaviortree_cpp_v3 binary package, instead of compiling behaviortree_cpp_v3 in the workspace.

**Comment by marioney** [comment]
> @chcorbato I suppose that in simulation, we can use standard eloquent binary installation.

Yes, I'm using the binary installation of eloquent.

> I have a binary installation now, but I get this error
> 
> ```
> ~/ros2_nav_dependencies_ws$   rosdep install -y -r -q --from-paths src --ignore-src --rosdistro eloquent
> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> behaviortree_cpp_v3: Cannot locate rosdep definition for [roslib]
> Continuing to install resolvable dependencies...
> #All required rosdeps installed successfully
> ```

I think you can safely ignore it, there's no installation candidate for eloquent and it doesn't seem to be needed in this case

**Comment by marioney** [comment]
> I think there is a typo in the new instruction to build `navigation2`, since they are the same than for the `ros2_nav_dependencies`:

You're right, thanks for noticing!

The typo is fixed on https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/commit/4d97cc2242c363b983aa5cf8c8aecb7185a19541

**Comment by chcorbato** [comment]
> I have a binary installation now, but I get this error
> 
> ```
> ~/ros2_nav_dependencies_ws$   rosdep install -y -r -q --from-paths src --ignore-src --rosdistro eloquent
> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> behaviortree_cpp_v3: Cannot locate rosdep definition for [roslib]
> Continuing to install resolvable dependencies...
> #All required rosdeps installed successfully
> ```

I installed the binary for `behaviortree_cpp_v3` and got rid of that error, thanks @fmrico 

Now, I get an error on `nav2_lifecycle_manager` when building the `navigation2`: 
```
Starting >>> nav2_lifecycle_manager                      
--- stderr: nav2_lifecycle_manager                                         
/home/chcorbato/navigation2_ws/install/nav2_util/lib/libnav2_util_core.so: undefined reference to `rclcpp::executor::Executor::spin_once_impl(std::chrono::duration<long, std::ratio<1l, 1000000000l> >)'
collect2: error: ld returned 1 exit status
make[2]: *** [lifecycle_manager] Error 1
make[1]: *** [CMakeFiles/lifecycle_manager.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< nav2_lifecycle_manager [12.4s, exited with code 2]
Aborted  <<< nav2_behavior_tree [29.9s]                               

Summary: 12 packages finished [35.9s]
  1 package failed: nav2_lifecycle_manager
  1 package aborted: nav2_behavior_tree
  1 package had stderr output: nav2_lifecycle_manager
  35 packages not processed
```

**Comment by fmrico** [comment]
These PRs are in review by @lbajo and @jginesclavero :

https://github.com/IntelligentRoboticsLabs/BICA/pull/13
#26 

As soon as they accept them, we could build the workspace without problems.

But your error looks very strange  Are you using an updated eloquent distro? Are you using the right version of repos?

**Comment by chcorbato** [comment]
> But your error looks very strange Are you using an updated eloquent distro? Are you using the right version of repos?

I am using Mario's instructions, so using the versions in there that he gathered.

I have just reinstalled [ROS2 eloquent](https://index.ros.org/doc/ros2/Installation/Eloquent/Linux-Install-Debians/)t, maybe the official binaries have been recently updated that that is the issue?

**Comment by fmrico** [comment]
Maybe we should rebase our contributions on top of release 0.3.4, which is the last official release of Nav2 for Eloquent. Or perhaps we should move to Foxy...

**Comment by chcorbato** [comment]
> I have a binary installation now
> [...]
> Now, I get an error on `nav2_lifecycle_manager` when building the `navigation2`:
> [...]

The problem here was that I had also installed the binaries of `navigation2` and `nav2-*`
After fixing that and moving to the branches corresponding to the PRs mentioned by @fmrico:
IntelligentRoboticsLabs/BICA#13
#26

I finally reached Mario's installation (I think):
```
Summary: 45 packages finished [2min 19s]
  1 package failed: bica_examples
  1 package aborted: nav2_system_tests
  1 package had stderr output: bica_examples
```

> Maybe we should rebase our contributions on top of release 0.3.4, which is the last official release of Nav2 for Eloquent. Or perhaps we should move to Foxy...

@ralph-lange @norro what do you think, for your SystemModes repository?

**Comment by norro** [comment]
The system modes package is available for dashing, eloquent, and foxy, so all of them should be fine from a system modes point-of-view.

**Comment by marioney** [comment]
I'm closing this as it's solved in https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/commit/e5726ee654ab0137be1d8f4aecdecc174967313f
