### ISSUE TITLE
Add turtlebot3 to the simulation options in the pilot

### ISSUE THREAD

**Issue by chcorbato** [MROS-RobMoSys-ITP/Pilot-URJC#27]
Currently, there is no bringup launchfile for turtlebot3 in `master`, but @marioney created it in `mario-tests`
Rationale for still wanting to be able to run this with turtlebot3 is that it does not require rosbridge, so it may be less cumbersome to set up for prototyping.

Fixes have been made in `master`. I suggest to create a pull request to merge the additional features in `mario-tests` to master.

Personally, I'm still struggling to get the complete thing up and running for turtlebot3.
I am currently using a mix of `master` and `mario-tests`

**Comment by jginesclavero** [comment]
Yes @marioney, create a pull request please.

**Comment by marioney** [comment]
> Yes @marioney, create a pull request please.

Ok, I've created the PR https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/pull/28

**Comment by marioney** [comment]
I'm closing this as #28 is merged 👍
