### ISSUE TITLE
Pilot-URJC in Foxy

### ISSUE THREAD

**Issue by chcorbato** [MROS-RobMoSys-ITP/Pilot-URJC#29]
I have upgraded to Ubuntu 20.04 and installed Foxy from debians.

I have created a new ws and followed from scratch the instructions here in the README (`master`) as they are, except replacing `eloquent` for `foxy`

I get an error in `navigation2/nav2_behavior_tree/`:

```
--- stderr: nav2_behavior_tree                                                                                            
In file included from /home/parallels/mros_ws/src/navigation2/nav2_behavior_tree/plugins/action/battery_warning.cpp:43:
/home/parallels/mros_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp: In member function ‘BT::NodeStatus nav2_behavior_tree::BtActionNode<ActionT>::tick()’:
/home/parallels/mros_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp:128:40: error: ‘using FutureReturnCode = enum class rclcpp::FutureReturnCode’ is deprecated: use rclcpp::FutureReturnCode instead [-Werror=deprecated-declarations]
  128 |     rclcpp::executor::FutureReturnCode rc;
      |                                        ^~
In file included from /opt/ros/foxy/include/rclcpp/executor.hpp:34,
                 from /opt/ros/foxy/include/rclcpp/executors/multi_threaded_executor.hpp:25,
                 from /opt/ros/foxy/include/rclcpp/executors.hpp:21,
                 from /opt/ros/foxy/include/rclcpp/rclcpp.hpp:146,
                 from /home/parallels/mros_ws/install/nav2_util/include/nav2_util/node_utils.hpp:19,
                 from /home/parallels/mros_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp:22,
                 from /home/parallels/mros_ws/src/navigation2/nav2_behavior_tree/plugins/action/battery_warning.cpp:43:
/opt/ros/foxy/include/rclcpp/future_return_code.hpp:48:7: note: declared here
   48 | using FutureReturnCode [[deprecated("use rclcpp::FutureReturnCode instead")]] = FutureReturnCode;
      |       ^~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_battery_warning_action_bt_node.dir/build.make:63: CMakeFiles/nav2_battery_warning_action_bt_node.dir/plugins/action/battery_warning.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:114: CMakeFiles/nav2_battery_warning_action_bt_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< nav2_behavior_tree [10.4s, exited with code 2]
Aborted  <<< plansys2_domain_expert [28.8s]                                         

Summary: 10 packages finished [2min 46s]
  1 package failed: nav2_behavior_tree
  1 package aborted: plansys2_domain_expert
  2 packages had stderr output: nav2_behavior_tree plansys2_domain_expert
  37 packages not processed
```

Which version of navigation2 should we follow for Foxy @fmrico ?

**Comment by fmrico** [comment]
Hi @chcorbato 

Maybe we have to sync our fork with master of Nav2. It is not done automatically.

Meanwhile, you could add a remote that points to official Nav2 and sync to master.

We should talk about this in the next meeting.

Best

**Comment by chcorbato** [comment]
> Hi @chcorbato
> 
> Maybe we have to sync our fork with master of Nav2. It is not done automatically.
> 
> Meanwhile, you could add a remote that points to official Nav2 and sync to master.

This error is in my second attempt, after adding official Nav2 as remote and syncing to tag 0.4.1, because `master` seems to be behind the foxy developments.

> We should talk about this in the next meeting.
> 
> Best

Yes, I think we need to discuss:
- What version of nav2 to sync to (`master`, `foxy-devel` or specific tags)
- How to maintain our fork synced

**Comment by fmrico** [comment]
@lbajo @jginesclavero Can you update the Readme for Foxy? There are still references to eloquent packages. Please, check these steps in Foxy.

**Comment by jginesclavero** [comment]
I'm working on it right now

**Comment by jginesclavero** [comment]
@fmrico @chcorbato The new instructions https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/pull/38

**Comment by fmrico** [comment]
Ok. As we clarified dependencies, branches, and everything seems to be working (checking in #38), we can close this issue. In any case, we can continue in #38 just in case of any problem there...
