### ISSUE TITLE
Add CI to all repos

### ISSUE THREAD

**Issue by fmrico** [MROS-RobMoSys-ITP/Pilot-URJC#31]
We should set up a Continous Integration system with Travis to ensure:

- clean code by linters
- Test in all the packages/components

**Comment by fmrico** [comment]
Hi @chcorbato 

I am trying to set up my travis account, giving rights to travis to access the repo. It has to be at the organization level, and only appears the organizations in which I am the owner. Is it possible to change my role from member to owner?

**Comment by chcorbato** [comment]
Hi @fmrico 

I am not familiar with Travis (just know it exists and vague idea of what it does):
- What does giving access to Travis implies for a repo?
- What will happen in those repositories that are not intended for executable code (we have one just for deliverables and another one for the ontologies)

**Comment by fmrico** [comment]
Hi @chcorbato 

Traves access to the repos for Continous Integration (CI). With CI, automatic tests are done in every pull request and commit in the repos that contain a `.travis` file in his root. We configure our repos to test:
- If compiles
- The style (linters)
- Unitary and integration tests

There is no problem with other repos without code.

**Comment by chcorbato** [comment]
Hi @fmrico 
Thanks for the explanation. Travis has been granted access for MROS-RobMoSys-ITP
