### ISSUE TITLE
Error installing Pilot

### ISSUE THREAD

**Issue by rsanz** [MROS-RobMoSys-ITP/Pilot-URJC#40]
Following the Pilot-URJC installation instructions in a brand new worskpace I get some dependency errors:
```
$  cd [ros2_ws]/src
...
$  git clone https://github.com/MROS-RobMoSys-ITP/Pilot-URJC.git
...
$  vcs import < Pilot-URJC/dependencies.repos
...
$  cd ..
$  rosdep install -y -r -q --from-paths src --ignore-src --rosdistro foxy

sanz@computer:~/ws$ rosdep install -y -r -q --from-paths src --ignore-src --rosdistro foxy
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
pilot_kobuki: Cannot locate rosdep definition for [turtlebot2_drivers]
nav2_bringup: Cannot locate rosdep definition for [slam_toolbox]
nav2_system_tests: Cannot locate rosdep definition for [gazebo_ros_pkgs]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
```

**Comment by jginesclavero** [comment]
Hi @rsanz ! You are in Ubuntu 20.04 and ROS2 Foxy, right?

**Comment by rsanz** [comment]
Yes.

**Comment by jginesclavero** [comment]
Try to run `sudo apt update` and rerun `rosdep install -y -r -q --from-paths src --ignore-src --rosdistro foxy`. 
If no effect, try to install gazebo_ros_pkgs manually with `sudo apt install ros-foxy-gazebo-ros-pkgs`.

**Comment by rsanz** [comment]
Thanks, Jonatan :+1: 

```sudo apt update``` had no effect (the system was already updated).

Hence ```rosdep install -y -r -q --from-paths src --ignore-src --rosdistro foxy``` had the same result as before.

Manual install of ```gazebo_ros_pkgs``` with ```sudo apt install ros-foxy-gazebo-ros-pkgs``` installed several packages (```ros-foxy-camera-calibration-parsers ros-foxy-camera-info-manager ros-foxy-gazebo-dev ros-foxy-gazebo-plugins ros-foxy-gazebo-ros ros-foxy-gazebo-ros-pkgs```).

This seemingly solved the problem with ```nav2_system_tests``` but not with ```pilot_kobuki``` nor ```nav2_bringup```.

Reruning ```rosdep install``` gives this:

```
sanz@computer:~/ws$ rosdep install -y -r -q --from-paths src --ignore-src --rosdistro foxy
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
pilot_kobuki: Cannot locate rosdep definition for [turtlebot2_drivers]
nav2_bringup: Cannot locate rosdep definition for [slam_toolbox]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
```

Doing a ```rosdep update``` solved the problem with ```nav2_bringup```. ```pilot_kobuki``` is still in trouble.

**Comment by jginesclavero** [comment]
OK! If you compile the workspace now, Do you see any dependencies error?

**Comment by fmrico** [comment]
Did you checked https://github.com/ros-planning/navigation2/blob/main/tools/underlay.repos, from https://navigation.ros.org/build_instructions/index.html#manually-build-main?

**Comment by rsanz** [comment]
@fmrico advice (special install instructions for Navigation2 in Ubuntu 20.04) solved the ```nav2_bringup``` problem.

When I build the workspace I just get a couple of warnings in ```pointcloud_to_laserscan``` (warning: no return statement in function returning non-void) that seem not important.

So, **it builds**. The ```pilot_kobuki``` dependency that ```rosdep``` complais about seems irrelvant.

Thanks !!!!

**Comment by chcorbato** [comment]
@rsanz which instructions solved your issue exactly? ["Manually Build Main in Navigation2 website"?](https://navigation.ros.org/build_instructions/index.html#build-ros-2-main)
@jginesclavero @fmrico is this something to add to the instructions, maybe as a footnote to solve known problems when installing the Pilot?

**Comment by rsanz** [comment]
This solved the nav2_bringup dependency problem:

For Ubuntu 20.04 use this command as the parsing of wildcards have been changed:

```sudo apt install ros-<distro>-navigation2 ros-<distro>-nav2-bringup '~ros-<distro>-turtlebot3-.*'````

**Comment by jginesclavero** [comment]
IMHO, install `ros-<distro>-navigation2 ros-<distro>-nav2-bringup` is a bad idea, because we have a fork of the navigation repo in MROS and could generate pkg collisions. I think that installing `sudo apt install ros-foxy-slam-toolbox ros-foxy-gazebo-ros-pkgs` must be enough.
