### ISSUE TITLE
Error during Pilot dependencies installation: packages/stacks could not have their rosdep keys resolved

### ISSUE THREAD

**Issue by chcorbato** [MROS-RobMoSys-ITP/Pilot-URJC#42]
Related to #40 
Following the README.md, in the step to install rosdep:

```console
$ rosdep install -y -r -q --from-paths src --ignore-src --rosdistro foxy
\ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
nav2_bringup: Cannot locate rosdep definition for [slam_toolbox]
pilot_kobuki: Cannot locate rosdep definition for [turtlebot2_drivers]
```

**Comment by jginesclavero** [comment]
Hi @chcorbato! Please, install slam-toolbox manually with `sudo apt install ros-foxy-slam-toolbox`. Another dependency is irrelevant. Then, try to compile and tell me if everything is ok.
Thank you!

**Comment by chcorbato** [comment]
I installed `slam-toolbox` and recompiled everything.
See #44 for the problem I have when running it for turtlebot3
Shall we add `slam-toolbox` installation to the README?

**Comment by jginesclavero** [comment]
Yes, I was waiting for your feedback. Thank you!!
