### ISSUE TITLE
Building error Readme turtlebot3

### ISSUE THREAD

**Issue by chcorbato** [MROS-RobMoSys-ITP/Pilot-URJC#43]
When following the Turtlebot3 installation instructions I get the following errors
```console
$ colcon build --symlink-install
[...]
Summary: 54 packages finished [1min 32s]
  2 packages had stderr output: dynamixel_sdk hls_lfcd_lds_driver
```

**Comment by jginesclavero** [comment]
It's only a warning from this packages, right?

**Comment by chcorbato** [comment]
Looks like, sorry I did not realize it did not report an error building those two packages.
