### ISSUE TITLE
Problem running Pilot for turtlebot3

### ISSUE THREAD

**Issue by chcorbato** [MROS-RobMoSys-ITP/Pilot-URJC#44]
After following the installation instructions for the Turtlebot3, I try to run it, but It seems there is a problem in relation to the transform from `/map` to `/odom` frames in RVIz, and the map is not visualized. Probably I'm doing something wrong when launching. Help is appreciated.

In one terminal I did (no apparent errors reported):
```console
$ ros2 launch pilot_urjc_bringup tb3_sim_launch.py 
```
In a second terminal:
```console
$ ros2 launch pilot_urjc_bringup nav2_turtlebot3_launch.py
[...]
[rviz2-1]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.4/src/buffer_core.cpp
[rviz2-1] Warning: Invalid frame ID "map" passed to canTransform argument source_frame - frame does not exist
```

**Comment by jginesclavero** [comment]
Yes, you must use our dummy_metacontroller and set the Normal Mode `ros2 run metacontroller_pilot metacontroller`.

**Comment by chcorbato** [comment]
Thanks! It works.
Maybe a idea to help clumsy people like me is to add in the README, for each main step in the deployment/usage:
- expected result (e.g. RVIz opens, you should see...)
- link to next step

**Comment by jginesclavero** [comment]
Ok! Thank you for your feedback. I will include in the next README's version.
