### ISSUE TITLE
gazebo model `nav2_house` not available 

### ISSUE THREAD

**Issue by marioney** [MROS-RobMoSys-ITP/Pilot-URJC#53]
The nav2_house model, https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/blob/9c4a706d73f8c730266f2c5fa2e92d4a0b4166a5/pilot_urjc_bringup/worlds/waffle_house.model#L49 that is required by the waffle_house.model used in the tb_sim3 launcher https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/blob/9c4a706d73f8c730266f2c5fa2e92d4a0b4166a5/pilot_urjc_bringup/launch/turtlebot3_sim/tb3_sim_launch.py#L73 is not avalable

Should it be included on the GAZEBO_MODEL_PATH variable?  or should we use a different world?

**Comment by jginesclavero** [comment]
In the README, the GAZEBO_MODEL_PATH already includes the path for nav2_house. I have just included it in MROS hands-on.
