### ISSUE TITLE
missing turtlebot2_drivers dep

### ISSUE THREAD

**Issue by norro** [MROS-RobMoSys-ITP/Pilot-URJC#54]
Step 6 of the installation instructions
`  rosdep install -y -r -q --from-paths src --ignore-src --rosdistro foxy`
fails with the following error:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
pilot_kobuki: Cannot locate rosdep definition for [turtlebot2_drivers]
Continuing to install resolvable dependencies...
```

Don't know if turtlebot2_drivers are still relevant, the rest of the installation is not missing it at least.

**Comment by fmrico** [comment]
Hi @norro 

I think that `turtlebot2_drivers` should be clone from [this](https://github.com/ros2/turtlebot2_demo), because it is not available from packages.

Best
